import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'ko' | 'en' | 'ja'

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// 번역 데이터 타입
type Translations = Record<string, string | Record<string, string>>

// 기본 번역 데이터 (한국어)
const defaultTranslations: Translations = {
  // App.tsx
  'app.title': '프롬프트 메이커',
  'app.subtitle': '텍스트, 이미지, 동영상 생성용 프롬프트를 생성합니다',
  'app.tab.text': '텍스트 콘텐츠',
  'app.tab.image': '이미지 생성',
  'app.tab.video': '동영상 생성',
  'app.tab.engineering': '프롬프트 엔지니어링',
  'app.tab.templates': '템플릿 갤러리',
  'app.tab.about': 'About',
  'app.admin': 'Admin',
  'app.adminTitle': '관리자 페이지로 이동',
  'app.footer.copyright': '© 2025 chunghyo park. Built to move the market. All rights reserved.',
  'app.footer.about': 'About',
  
  // 공통
  'common.select': '선택 안함',
  'common.submit': '제출',
  'common.cancel': '취소',
  'common.close': '닫기',
  'common.save': '저장',
  'common.delete': '삭제',
  'common.edit': '편집',
  'common.loading': '로딩 중...',
  'common.error': '오류가 발생했습니다',
  
  // 테마
  'theme.label': '테마',
  'theme.light': '라이트 모드',
  'theme.dark': '다크 모드',
  'theme.system': '시스템 모드',
  
  // 언어
  'language.label': '언어',
  'language.ko': '한국어',
  'language.en': 'English',
  'language.ja': '日本語',
  
  // PromptGenerator
  'prompt.mode.guide': '가이드 모드',
  'prompt.mode.advanced': '고급 모드',
  'prompt.mode.guideDesc': '단계별 안내를 따라 프롬프트를 완성하세요.',
  'prompt.mode.advancedDesc': '모든 옵션을 한 번에 설정하세요.',
  'prompt.wizard.step1': '목표 & 채널',
  'prompt.wizard.step2': '타겟 & 톤',
  'prompt.wizard.step3': '자연어 프롬프트',
  'prompt.wizard.step4': '구조화 프리뷰',
  'prompt.wizard.hint1': '생성하고자 하는 채널과 목적을 먼저 정의하면 이후 단계에서 맞춤 가이드를 받을 수 있습니다.',
  'prompt.wizard.hint2': '타겟 독자와 어투를 선택하면 템플릿의 페르소나와 톤 섹션이 함께 채워집니다.',
  'prompt.wizard.hint3': '자연어로 원하는 내용을 자유롭게 작성하면 컨텍스트 템플릿의 상황/지시/요약이 자동으로 구성됩니다.',
  'prompt.wizard.hint4': '입력값으로 생성될 템플릿을 미리 확인한 뒤 최종 출력을 생성하세요.',
  'prompt.wizard.summary': '선택한 채널에 맞춰 메타 템플릿이 자동 구성됩니다.',
  'prompt.wizard.summaryItem': '목표/주제/타겟/제약/톤/출력 구조를 자동 정렬',
  'prompt.wizard.previewEmpty': '프롬프트를 입력하면 미리보기가 표시됩니다.',
  'prompt.wizard.prev': '이전 단계',
  'prompt.wizard.next': '다음 단계',
  'prompt.wizard.generate': '프롬프트 생성하기',
  'prompt.wizard.generating': '생성 중...',
  'prompt.contentType.label': '콘텐츠 유형 선택',
  'prompt.contentType.blog': '블로그 콘텐츠',
  'prompt.contentType.linkedin': '링크드인 뉴스피드',
  'prompt.contentType.facebook': '페이스북 뉴스피드',
  'prompt.contentType.instagram': '인스타그램 뉴스피드',
  'prompt.contentType.youtube': '유튜브 영상',
  'prompt.contentType.twitter': 'X (Twitter)',
  'prompt.contentType.threads': 'Threads',
  'prompt.contentType.tiktok': 'TikTok',
  'prompt.contentType.podcast': '팟캐스트',
  'prompt.contentType.email': '이메일 마케팅',
  'prompt.contentType.newsletter': '뉴스레터',
  'prompt.contentType.product': '제품 설명서',
  'prompt.contentType.faq': 'FAQ',
  'prompt.contentType.general': '일반 텍스트',
  'prompt.goal.label': '콘텐츠 목표',
  'prompt.goal.hint': '목표에 맞춰 템플릿과 가이드라인이 자동으로 업데이트됩니다.',
  'prompt.goal.awareness': '브랜드 인지도 강화',
  'prompt.goal.conversion': '전환/구매 유도',
  'prompt.goal.engagement': '참여/소통 활성화',
  'prompt.goal.education': '교육/인사이트 제공',
  'prompt.goal.leadGeneration': '리드 생성/수집',
  'prompt.goal.retention': '고객 유지/리텐션',
  'prompt.goal.productPromotion': '제품/서비스 홍보',
  'prompt.goal.traffic': '웹사이트 트래픽 유도',
  'prompt.goal.authority': '권위/전문성 구축',
  'prompt.goal.customerSupport': '고객 지원/FAQ',
  'prompt.goal.eventPromotion': '이벤트/프로모션 안내',
  'prompt.goal.newsAnnouncement': '뉴스/공지사항',
  'prompt.goal.communityBuilding': '커뮤니티 구축',
  'prompt.goal.thoughtLeadership': '사고 리더십 발휘',
  'prompt.input.label': '자연어 프롬프트 입력',
  'prompt.input.placeholder': '예: 인공지능의 미래와 사회적 영향에 대해 작성해주세요',
  'prompt.input.length': '입력 길이',
  'prompt.input.chars': 'chars',
  'prompt.details.toggle': '상세 옵션',
  'prompt.details.expand': '펼치기',
  'prompt.details.collapse': '접기',
  'prompt.age.label': '나이',
  'prompt.age.none': '선택 안함',
  'prompt.age.10s': '10대',
  'prompt.age.20s': '20대',
  'prompt.age.30s': '30대',
  'prompt.age.40s': '40대',
  'prompt.age.50s': '50대',
  'prompt.age.60plus': '60대 이상',
  'prompt.gender.label': '성별',
  'prompt.gender.male': '남성',
  'prompt.gender.female': '여성',
  'prompt.gender.any': '무관',
  'prompt.occupation.label': '타겟의 직업',
  'prompt.occupation.student': '학생',
  'prompt.occupation.worker': '직장인',
  'prompt.occupation.developer': '개발자/프로그래머',
  'prompt.occupation.designer': '디자이너',
  'prompt.occupation.marketer': '마케터',
  'prompt.occupation.planner': '기획자',
  'prompt.occupation.ceo': '경영진/CEO',
  'prompt.occupation.selfEmployed': '자영업자',
  'prompt.occupation.freelancer': '프리랜서',
  'prompt.occupation.professional': '전문직',
  'prompt.occupation.other': '기타',
  'prompt.tone.label': '어투 및 말 표현',
  'prompt.tone.conversational': '대화체',
  'prompt.tone.conversationalDesc': '구어체, 친근한 대화 형식',
  'prompt.tone.formal': '격식체',
  'prompt.tone.formalDesc': '정중하고 격식 있는 표현',
  'prompt.tone.friendly': '친근한 말투',
  'prompt.tone.friendlyDesc': '따뜻하고 친근한 톤',
  'prompt.tone.professional': '전문적인 말투',
  'prompt.tone.professionalDesc': '전문적이고 신뢰감 있는 표현',
  'prompt.tone.casual': '캐주얼한 말투',
  'prompt.tone.casualDesc': '편안하고 부담 없는 표현',
  'prompt.tone.polite': '정중한 말투',
  'prompt.tone.politeDesc': '예의 바르고 정중한 표현',
  'prompt.tone.concise': '간결한 말투',
  'prompt.tone.conciseDesc': '명확하고 간결한 표현',
  'prompt.tone.explanatory': '설명적인 말투',
  'prompt.tone.explanatoryDesc': '상세하고 이해하기 쉬운 설명',
  'prompt.loading': '프롬프트를 생성하고 있습니다...',
  'prompt.error.required': '프롬프트를 입력해주세요.',
  'prompt.error.generation': '프롬프트 생성 중 오류가 발생했습니다.',
  'prompt.result.guideApplied': '모델 가이드 반영됨',
  'prompt.result.confidence': '신뢰도',
  'prompt.result.guideDefault': '최신 가이드라인이 적용되었습니다.',
  'prompt.result.metaTemplate': '표준 메타 프롬프트 템플릿',
  'prompt.result.metaPrompt': '메타 프롬프트',
  'prompt.result.contextTemplate': '컨텍스트 프롬프트 템플릿',
  'prompt.result.contextPrompt': '컨텍스트 프롬프트',
  'prompt.result.hashtags': '해시태그',
  'prompt.result.hashtagsCopy': '해시태그 복사',
  'prompt.result.hashtagsCopied': '✓ 복사됨',
  'prompt.result.previewMeta': '메타 템플릿 미리보기',
  'prompt.result.previewContext': '컨텍스트 템플릿 미리보기',
  'prompt.guideline.blog': 'SEO 키워드',
  'prompt.guideline.blog2': '질문 기반 서술',
  'prompt.guideline.blog3': 'CTA 포함',
  'prompt.guideline.linkedin': '전문 인사이트',
  'prompt.guideline.linkedin2': '네트워킹 유도',
  'prompt.guideline.linkedin3': '전문 톤',
  'prompt.guideline.facebook': '친근한 톤',
  'prompt.guideline.facebook2': '질문 던지기',
  'prompt.guideline.facebook3': '공유 유도',
  'prompt.guideline.instagram': '감성적 표현',
  'prompt.guideline.instagram2': '해시태그 최적화',
  'prompt.guideline.instagram3': 'CTA',
  'prompt.guideline.youtube': '검색 키워드',
  'prompt.guideline.youtube2': '훅 문장',
  'prompt.guideline.youtube3': '타임스탬프',
  'prompt.guideline.general': '의도 명확화',
  'prompt.guideline.general2': '자연어 유지',
  'prompt.guideline.general3': '핵심 메시지',
}

// 영어 번역
const enTranslations: Translations = {
  ...defaultTranslations,
  'app.title': 'Prompt Maker',
  'app.subtitle': 'Generate prompts for text, image, and video generation',
  'app.tab.text': 'Text Content',
  'app.tab.image': 'Image Generation',
  'app.tab.video': 'Video Generation',
  'app.tab.engineering': 'Prompt Engineering',
  'app.tab.templates': 'Template Gallery',
  'app.tab.about': 'About',
  'app.adminTitle': 'Go to admin page',
  'app.footer.copyright': '© 2025 chunghyo park. Built to move the market. All rights reserved.',
  'common.select': 'None',
  'common.submit': 'Submit',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.loading': 'Loading...',
  'common.error': 'An error occurred',
  'theme.label': 'Theme',
  'theme.light': 'Light Mode',
  'theme.dark': 'Dark Mode',
  'theme.system': 'System Mode',
  'language.label': 'Language',
  'language.ko': 'Korean',
  'language.en': 'English',
  'language.ja': 'Japanese',
  
  // PromptGenerator
  'prompt.mode.guide': 'Guide Mode',
  'prompt.mode.advanced': 'Advanced Mode',
  'prompt.mode.guideDesc': 'Complete your prompt by following step-by-step guidance.',
  'prompt.mode.advancedDesc': 'Set all options at once.',
  'prompt.wizard.step1': 'Goal & Channel',
  'prompt.wizard.step2': 'Target & Tone',
  'prompt.wizard.step3': 'Natural Language Prompt',
  'prompt.wizard.step4': 'Structured Preview',
  'prompt.wizard.hint1': 'Define the channel and purpose first to receive customized guidance in subsequent steps.',
  'prompt.wizard.hint2': 'Selecting target audience and tone will automatically fill the persona and tone sections of the template.',
  'prompt.wizard.hint3': 'Write your desired content in natural language, and the context template will automatically organize situation/instructions/summary.',
  'prompt.wizard.hint4': 'Preview the template that will be generated from your input before creating the final output.',
  'prompt.wizard.summary': 'Meta template is automatically configured according to the selected channel.',
  'prompt.wizard.summaryItem': 'Auto-align goal/topic/target/constraints/tone/output structure',
  'prompt.wizard.previewEmpty': 'Enter a prompt to see the preview.',
  'prompt.wizard.prev': 'Previous Step',
  'prompt.wizard.next': 'Next Step',
  'prompt.wizard.generate': 'Generate Prompt',
  'prompt.wizard.generating': 'Generating...',
  'prompt.contentType.label': 'Select Content Type',
  'prompt.contentType.blog': 'Blog Content',
  'prompt.contentType.linkedin': 'LinkedIn Feed',
  'prompt.contentType.facebook': 'Facebook Feed',
  'prompt.contentType.instagram': 'Instagram Feed',
  'prompt.contentType.youtube': 'YouTube Video',
  'prompt.contentType.twitter': 'X (Twitter)',
  'prompt.contentType.threads': 'Threads',
  'prompt.contentType.tiktok': 'TikTok',
  'prompt.contentType.podcast': 'Podcast',
  'prompt.contentType.email': 'Email Marketing',
  'prompt.contentType.newsletter': 'Newsletter',
  'prompt.contentType.product': 'Product Description',
  'prompt.contentType.faq': 'FAQ',
  'prompt.contentType.general': 'General Text',
  'prompt.goal.label': 'Content Goal',
  'prompt.goal.hint': 'Templates and guidelines are automatically updated according to the goal.',
  'prompt.goal.awareness': 'Brand Awareness',
  'prompt.goal.conversion': 'Conversion/Purchase',
  'prompt.goal.engagement': 'Engagement/Interaction',
  'prompt.goal.education': 'Education/Insights',
  'prompt.goal.leadGeneration': 'Lead Generation',
  'prompt.goal.retention': 'Customer Retention',
  'prompt.goal.productPromotion': 'Product/Service Promotion',
  'prompt.goal.traffic': 'Website Traffic',
  'prompt.goal.authority': 'Authority/Expertise',
  'prompt.goal.customerSupport': 'Customer Support/FAQ',
  'prompt.goal.eventPromotion': 'Event/Promotion',
  'prompt.goal.newsAnnouncement': 'News/Announcement',
  'prompt.goal.communityBuilding': 'Community Building',
  'prompt.goal.thoughtLeadership': 'Thought Leadership',
  'prompt.input.label': 'Enter Natural Language Prompt',
  'prompt.input.placeholder': 'e.g., Please write about the future of AI and its social impact',
  'prompt.input.length': 'Input Length',
  'prompt.input.chars': 'chars',
  'prompt.details.toggle': 'Detailed Options',
  'prompt.details.expand': 'Expand',
  'prompt.details.collapse': 'Collapse',
  'prompt.age.label': 'Age',
  'prompt.age.none': 'None',
  'prompt.age.10s': '10s',
  'prompt.age.20s': '20s',
  'prompt.age.30s': '30s',
  'prompt.age.40s': '40s',
  'prompt.age.50s': '50s',
  'prompt.age.60plus': '60+',
  'prompt.gender.label': 'Gender',
  'prompt.gender.male': 'Male',
  'prompt.gender.female': 'Female',
  'prompt.gender.any': 'Any',
  'prompt.occupation.label': 'Target Occupation',
  'prompt.occupation.student': 'Student',
  'prompt.occupation.worker': 'Worker',
  'prompt.occupation.developer': 'Developer/Programmer',
  'prompt.occupation.designer': 'Designer',
  'prompt.occupation.marketer': 'Marketer',
  'prompt.occupation.planner': 'Planner',
  'prompt.occupation.ceo': 'Executive/CEO',
  'prompt.occupation.selfEmployed': 'Self-Employed',
  'prompt.occupation.freelancer': 'Freelancer',
  'prompt.occupation.professional': 'Professional',
  'prompt.occupation.other': 'Other',
  'prompt.tone.label': 'Tone & Style',
  'prompt.tone.conversational': 'Conversational',
  'prompt.tone.conversationalDesc': 'Colloquial, friendly conversation style',
  'prompt.tone.formal': 'Formal',
  'prompt.tone.formalDesc': 'Polite and formal expression',
  'prompt.tone.friendly': 'Friendly',
  'prompt.tone.friendlyDesc': 'Warm and friendly tone',
  'prompt.tone.professional': 'Professional',
  'prompt.tone.professionalDesc': 'Professional and trustworthy expression',
  'prompt.tone.casual': 'Casual',
  'prompt.tone.casualDesc': 'Relaxed and comfortable expression',
  'prompt.tone.polite': 'Polite',
  'prompt.tone.politeDesc': 'Courteous and polite expression',
  'prompt.tone.concise': 'Concise',
  'prompt.tone.conciseDesc': 'Clear and concise expression',
  'prompt.tone.explanatory': 'Explanatory',
  'prompt.tone.explanatoryDesc': 'Detailed and easy-to-understand explanation',
  'prompt.loading': 'Generating prompt...',
  'prompt.error.required': 'Please enter a prompt.',
  'prompt.error.generation': 'An error occurred while generating the prompt.',
  'prompt.result.guideApplied': 'Model Guide Applied',
  'prompt.result.confidence': 'Confidence',
  'prompt.result.guideDefault': 'Latest guidelines have been applied.',
  'prompt.result.metaTemplate': 'Standard Meta Prompt Template',
  'prompt.result.metaPrompt': 'Meta Prompt',
  'prompt.result.contextTemplate': 'Context Prompt Template',
  'prompt.result.contextPrompt': 'Context Prompt',
  'prompt.result.hashtags': 'Hashtags',
  'prompt.result.hashtagsCopy': 'Copy Hashtags',
  'prompt.result.hashtagsCopied': '✓ Copied',
  'prompt.result.previewMeta': 'Meta Template Preview',
  'prompt.result.previewContext': 'Context Template Preview',
  'prompt.guideline.blog': 'SEO Keywords',
  'prompt.guideline.blog2': 'Question-based Narrative',
  'prompt.guideline.blog3': 'Include CTA',
  'prompt.guideline.linkedin': 'Professional Insights',
  'prompt.guideline.linkedin2': 'Networking Encouragement',
  'prompt.guideline.linkedin3': 'Professional Tone',
  'prompt.guideline.facebook': 'Friendly Tone',
  'prompt.guideline.facebook2': 'Ask Questions',
  'prompt.guideline.facebook3': 'Encourage Sharing',
  'prompt.guideline.instagram': 'Emotional Expression',
  'prompt.guideline.instagram2': 'Hashtag Optimization',
  'prompt.guideline.instagram3': 'CTA',
  'prompt.guideline.youtube': 'Search Keywords',
  'prompt.guideline.youtube2': 'Hook Sentence',
  'prompt.guideline.youtube3': 'Timestamp',
  'prompt.guideline.general': 'Clarify Intent',
  'prompt.guideline.general2': 'Maintain Natural Language',
  'prompt.guideline.general3': 'Core Message',
}

// 일본어 번역
const jaTranslations: Translations = {
  ...defaultTranslations,
  'app.title': 'プロンプトメーカー',
  'app.subtitle': 'テキスト、画像、動画生成用のプロンプトを生成します',
  'app.tab.text': 'テキストコンテンツ',
  'app.tab.image': '画像生成',
  'app.tab.video': '動画生成',
  'app.tab.engineering': 'プロンプトエンジニアリング',
  'app.tab.templates': 'テンプレートギャラリー',
  'app.tab.about': 'About',
  'app.adminTitle': '管理者ページに移動',
  'app.footer.copyright': '© 2025 chunghyo park. Built to move the market. All rights reserved.',
  'common.select': '選択なし',
  'common.submit': '送信',
  'common.cancel': 'キャンセル',
  'common.close': '閉じる',
  'common.save': '保存',
  'common.delete': '削除',
  'common.edit': '編集',
  'common.loading': '読み込み中...',
  'common.error': 'エラーが発生しました',
  'theme.label': 'テーマ',
  'theme.light': 'ライトモード',
  'theme.dark': 'ダークモード',
  'theme.system': 'システムモード',
  'language.label': '言語',
  'language.ko': '韓国語',
  'language.en': '英語',
  'language.ja': '日本語',
  
  // PromptGenerator
  'prompt.mode.guide': 'ガイドモード',
  'prompt.mode.advanced': '詳細モード',
  'prompt.mode.guideDesc': 'ステップバイステップのガイドに従ってプロンプトを完成させてください。',
  'prompt.mode.advancedDesc': 'すべてのオプションを一度に設定してください。',
  'prompt.wizard.step1': '目標 & チャネル',
  'prompt.wizard.step2': 'ターゲット & トーン',
  'prompt.wizard.step3': '自然言語プロンプト',
  'prompt.wizard.step4': '構造化プレビュー',
  'prompt.wizard.hint1': '作成したいチャネルと目的を最初に定義すると、以降のステップでカスタマイズされたガイドを受けることができます。',
  'prompt.wizard.hint2': 'ターゲット読者と語調を選択すると、テンプレートのペルソナとトーンセクションが一緒に埋められます。',
  'prompt.wizard.hint3': '自然言語で希望する内容を自由に記述すると、コンテキストテンプレートの状況/指示/要約が自動的に構成されます。',
  'prompt.wizard.hint4': '入力値から生成されるテンプレートを事前に確認してから最終出力を生成してください。',
  'prompt.wizard.summary': '選択したチャネルに合わせてメタテンプレートが自動構成されます。',
  'prompt.wizard.summaryItem': '目標/主題/ターゲット/制約/トーン/出力構造を自動整列',
  'prompt.wizard.previewEmpty': 'プロンプトを入力するとプレビューが表示されます。',
  'prompt.wizard.prev': '前のステップ',
  'prompt.wizard.next': '次のステップ',
  'prompt.wizard.generate': 'プロンプト生成',
  'prompt.wizard.generating': '生成中...',
  'prompt.contentType.label': 'コンテンツタイプ選択',
  'prompt.contentType.blog': 'ブログコンテンツ',
  'prompt.contentType.linkedin': 'LinkedInフィード',
  'prompt.contentType.facebook': 'Facebookフィード',
  'prompt.contentType.instagram': 'Instagramフィード',
  'prompt.contentType.youtube': 'YouTube動画',
  'prompt.contentType.twitter': 'X (Twitter)',
  'prompt.contentType.threads': 'Threads',
  'prompt.contentType.tiktok': 'TikTok',
  'prompt.contentType.podcast': 'ポッドキャスト',
  'prompt.contentType.email': 'メールマーケティング',
  'prompt.contentType.newsletter': 'ニュースレター',
  'prompt.contentType.product': '製品説明書',
  'prompt.contentType.faq': 'FAQ',
  'prompt.contentType.general': '一般テキスト',
  'prompt.goal.label': 'コンテンツ目標',
  'prompt.goal.hint': '目標に合わせてテンプレートとガイドラインが自動的に更新されます。',
  'prompt.goal.awareness': 'ブランド認知度強化',
  'prompt.goal.conversion': '転換/購入誘導',
  'prompt.goal.engagement': '参加/交流活性化',
  'prompt.goal.education': '教育/インサイト提供',
  'prompt.goal.leadGeneration': 'リード生成/収集',
  'prompt.goal.retention': '顧客維持/リテンション',
  'prompt.goal.productPromotion': '製品/サービス宣伝',
  'prompt.goal.traffic': 'ウェブサイトトラフィック誘導',
  'prompt.goal.authority': '権威/専門性構築',
  'prompt.goal.customerSupport': '顧客サポート/FAQ',
  'prompt.goal.eventPromotion': 'イベント/プロモーション案内',
  'prompt.goal.newsAnnouncement': 'ニュース/お知らせ',
  'prompt.goal.communityBuilding': 'コミュニティ構築',
  'prompt.goal.thoughtLeadership': '思想リーダーシップ発揮',
  'prompt.input.label': '自然言語プロンプト入力',
  'prompt.input.placeholder': '例：人工知能の未来と社会的影響について書いてください',
  'prompt.input.length': '入力長',
  'prompt.input.chars': '文字',
  'prompt.details.toggle': '詳細オプション',
  'prompt.details.expand': '展開',
  'prompt.details.collapse': '折りたたみ',
  'prompt.age.label': '年齢',
  'prompt.age.none': '選択なし',
  'prompt.age.10s': '10代',
  'prompt.age.20s': '20代',
  'prompt.age.30s': '30代',
  'prompt.age.40s': '40代',
  'prompt.age.50s': '50代',
  'prompt.age.60plus': '60代以上',
  'prompt.gender.label': '性別',
  'prompt.gender.male': '男性',
  'prompt.gender.female': '女性',
  'prompt.gender.any': '無関係',
  'prompt.occupation.label': 'ターゲットの職業',
  'prompt.occupation.student': '学生',
  'prompt.occupation.worker': '会社員',
  'prompt.occupation.developer': '開発者/プログラマー',
  'prompt.occupation.designer': 'デザイナー',
  'prompt.occupation.marketer': 'マーケター',
  'prompt.occupation.planner': '企画者',
  'prompt.occupation.ceo': '経営陣/CEO',
  'prompt.occupation.selfEmployed': '自営業',
  'prompt.occupation.freelancer': 'フリーランサー',
  'prompt.occupation.professional': '専門職',
  'prompt.occupation.other': 'その他',
  'prompt.tone.label': '語調と表現',
  'prompt.tone.conversational': '会話体',
  'prompt.tone.conversationalDesc': '口語体、親しみやすい会話形式',
  'prompt.tone.formal': '格式体',
  'prompt.tone.formalDesc': '丁寧で格式のある表現',
  'prompt.tone.friendly': '親しみやすい口調',
  'prompt.tone.friendlyDesc': '温かく親しみやすいトーン',
  'prompt.tone.professional': '専門的な口調',
  'prompt.tone.professionalDesc': '専門的で信頼感のある表現',
  'prompt.tone.casual': 'カジュアルな口調',
  'prompt.tone.casualDesc': 'リラックスして負担のない表現',
  'prompt.tone.polite': '丁寧な口調',
  'prompt.tone.politeDesc': '礼儀正しく丁寧な表現',
  'prompt.tone.concise': '簡潔な口調',
  'prompt.tone.conciseDesc': '明確で簡潔な表現',
  'prompt.tone.explanatory': '説明的な口調',
  'prompt.tone.explanatoryDesc': '詳細で理解しやすい説明',
  'prompt.loading': 'プロンプトを生成しています...',
  'prompt.error.required': 'プロンプトを入力してください。',
  'prompt.error.generation': 'プロンプト生成中にエラーが発生しました。',
  'prompt.result.guideApplied': 'モデルガイド反映',
  'prompt.result.confidence': '信頼度',
  'prompt.result.guideDefault': '最新のガイドラインが適用されました。',
  'prompt.result.metaTemplate': '標準メタプロンプトテンプレート',
  'prompt.result.metaPrompt': 'メタプロンプト',
  'prompt.result.contextTemplate': 'コンテキストプロンプトテンプレート',
  'prompt.result.contextPrompt': 'コンテキストプロンプト',
  'prompt.result.hashtags': 'ハッシュタグ',
  'prompt.result.hashtagsCopy': 'ハッシュタグコピー',
  'prompt.result.hashtagsCopied': '✓ コピー済み',
  'prompt.result.previewMeta': 'メタテンプレートプレビュー',
  'prompt.result.previewContext': 'コンテキストテンプレートプレビュー',
  'prompt.guideline.blog': 'SEOキーワード',
  'prompt.guideline.blog2': '質問ベースの記述',
  'prompt.guideline.blog3': 'CTA含む',
  'prompt.guideline.linkedin': '専門インサイト',
  'prompt.guideline.linkedin2': 'ネットワーキング誘導',
  'prompt.guideline.linkedin3': '専門トーン',
  'prompt.guideline.facebook': '親しみやすいトーン',
  'prompt.guideline.facebook2': '質問を投げかける',
  'prompt.guideline.facebook3': '共有誘導',
  'prompt.guideline.instagram': '感情的な表現',
  'prompt.guideline.instagram2': 'ハッシュタグ最適化',
  'prompt.guideline.instagram3': 'CTA',
  'prompt.guideline.youtube': '検索キーワード',
  'prompt.guideline.youtube2': 'フック文',
  'prompt.guideline.youtube3': 'タイムスタンプ',
  'prompt.guideline.general': '意図の明確化',
  'prompt.guideline.general2': '自然言語維持',
  'prompt.guideline.general3': '核心メッセージ',
}

const translations: Record<Language, Translations> = {
  ko: defaultTranslations,
  en: enTranslations,
  ja: jaTranslations,
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // localStorage에서 언어 설정 불러오기
    const saved = localStorage.getItem('language')
    if (saved === 'ko' || saved === 'en' || saved === 'ja') {
      return saved
    }
    // 브라우저 언어 감지
    const browserLang = navigator.language.toLowerCase()
    if (browserLang.startsWith('ko')) return 'ko'
    if (browserLang.startsWith('ja')) return 'ja'
    return 'en'
  })

  useEffect(() => {
    // 언어 설정을 localStorage에 저장
    localStorage.setItem('language', language)
    // HTML lang 속성 업데이트
    document.documentElement.lang = language
  }, [language])

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
  }

  const t = (key: string, params?: Record<string, string | number>): string => {
    const translation = translations[language]
    let value = translation[key] || defaultTranslations[key] || key

    // 중첩된 키 지원 (예: 'common.button.submit')
    if (typeof value === 'object') {
      // 중첩된 객체인 경우, 더 깊은 키 탐색 필요
      const keys = key.split('.')
      let current: any = translation
      for (const k of keys) {
        current = current?.[k]
        if (!current) break
      }
      value = current || key
    }

    // 파라미터 치환
    if (params && typeof value === 'string') {
      return value.replace(/\{\{(\w+)\}\}/g, (match, paramKey) => {
        return params[paramKey]?.toString() || match
      })
    }

    return typeof value === 'string' ? value : key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// 번역 함수를 직접 export (컴포넌트 외부에서 사용)
export function getTranslation(language: Language, key: string): string {
  const translation = translations[language]
  const value = translation[key] || translations.ko[key] || key
  return typeof value === 'string' ? value : key
}
